config/routes.rb
Twitter::Application.routes.draw do
  get "home" => "pages#home"
  root :to => "user#new"

  resources :user
  

  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :password

before_save :encrypt_password
validates_confirmation_of :password
validates_presence_of :password, :on => :create
validates_presence_of :email
validates_uniqueness_of :email
has_many :tweets

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
	  def new
	  	@user = User.new
	  end

	def create 
		@user = User.create(user_params)
		if @user.save
			redirect_to home_path, :notice => "signed up!"
		else
			render "new"
		end
	end

	private 

	def user_params
		params.require(:user).permit(:f_name, :l_name, :email, :username, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Twitter
    = stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "bootstrap", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body.container
	
		.navbar
			.navbar-inner
				%a.brand{:href => "#"} Title
				%ul.nav
					%li.active
						%a{:href => "#"} Home
					%li
						%a{:href => "#"} Link
					%li
						%a{:href => "#"} Link
    = yield

app/views/pages/home.html.haml
%h1 Pages#home
%p Find me in app/views/pages/home.html.haml

app/views/user/new.haml
.container
	.row
		.span12
			%h1 Sign Up
			=form_for @user, :url => user_index_path do |f| 
				=f.label "First Name"
				=f.text_field :f_name
				=f.label "Last Name"
				=f.text_field :l_name
				=f.label "Email"
				=f.text_field :email
				=f.label "Username"
				=f.text_field :username
				=f.label "Password"
				=f.password_field :password
				=f.label "Password confirmation"
				=f.password_field :password_confirmation
				%br
				=f.submit :class=>"btn"